#!/bin/bash
# Usage: scan_perpage <imagefile>
#   where imagefile is the data just scanned
# (specify this script to scanadf via -S)

usage()
{
  echo "Usage: $0 <imagefile>"
  echo "Set the following environment variables:"
  echo "  unpaper"
  echo "  searchable"
  echo "  language"
  echo "  resolution"
  echo "  pgwidthin"
  echo "  pgheightin"
  echo "  skip_empty_pages"
  echo "  ps2pdf_opts (optional)"
  echo "  verbose (optional)"
  echo "  lockfile (required if verbose=1)"
}

log()
{
  if [ $verbose = 1 ]; then
    echo "scan_perpage: $1"
  fi
}

logstdout()
{
  if [ $verbose = 1 ]; then
    cat
  else
    cat > /dev/null
  fi
}

if [ $# -lt 1 ]; then
  usage
  exit 1
fi

if [ "$unpaper" == "" -o "$searchable" == "" -o "$resolution" == "" -o "$resolution" == "" -o "$skip_empty_pages" == "" ]; then
  usage
  exit 1
fi

image_path=$1
image_dir=$(dirname $1)
image_file=$(basename $1)

process_page() {
  log ""
  log "-------------------------------------------------------------------------------"
  log "Post-processing scanned page ${image_file}, deskew=$unpaper, searchable=$searchable..."

  
  [[ $skip_empty_pages -eq 1 ]] && percentage_white=$(convert "$image_path" -fuzz 0% -negate -threshold 0 -negate -format "%[fx:100*mean]" info:) || percentage_white=0
  log "$image_path has $percentage_white % white"
    
  pp_prefix=
  if (( $(echo "$percentage_white < 99.8" |bc -l) )); then
    if [ $unpaper -eq 1 ]; then
      log "Applying unpaper post-processing to image data..."
      pp_prefix="unpaper-"
      if [ $verbose = 1 ]; then
        unpaperverbose="-v"
      fi
      #unpaper $unpaperverbose --no-mask-scan --overwrite --dpi $resolution --no-blackfilter $image_file $pp_prefix$image_file | logstdout
      unpaper $unpaperverbose --overwrite --dpi $resolution $image_path $image_dir/$pp_prefix$image_file | logstdout
    fi
    log ""
    log "-------------------------------------------------------------------------------"
    if [ $searchable -eq 1 ]; then
      log "Converting image data to searchable pdf..."
      tesseract $image_dir/$pp_prefix$image_file $image_dir/${image_file%.*} -l $language pdf | logstdout
    else
      log "Converting image data to pdf..."
      pnmverbose=
      if [ $verbose = 1 ]; then
        pnmverbose="-verbose"
      fi
      if [ "$pgwidthin" == "" -o "$pgheightin" == "" ]; then
        pageopts="-equalpixels -dpi=$resolution -noturn"
      else
        pageopts="-imagewidth $pgwidthin -imageheight $pgheightin"
      fi
      log "Using page options: $pageopts"
      pnmtops $pnmverbose $pageopts $image_dir/$pp_prefix$image_file | ps2pdf $ps2pdf_opts - > $image_dir/${image_file%.*}.pdf | logstdout
    fi    
  else
    log "Skipping empty page $image_file with white percentage $percentage_white"
  fi
  
  status=$?
  rm $image_path
  if [ -f $image_dir/$pp_prefix$image_file ]; then
    rm $image_dir/$pp_prefix$image_file
  fi

  log ""
  log "Scan processing done, status = $status"
}

if [ $verbose = 1 ]; then
  (
    flock 200
    process_page
  ) 200>$lockfile
else
  process_page
fi;

exit $status
